kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
        app: api
    spec:
      containers:
      - name: api
        image: pskreter/personalapi-api:0.0.1
        ports:
        - name: admin
          containerPort: 80
          protocol: TCP
