kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
        app: frontend
    spec:
      containers:
      - name: reactapp
        image: pskreter/personalapi-frontend
        ports:
        - name: admin
          containerPort: 80
          protocol: TCP
